from enum import Enum


class FindingsAcceptRisksCreateOItem(str, Enum):
    ACTIVE = "active"
    COMPONENT_NAME = "component_name"
    COMPONENT_VERSION = "component_version"
    CREATED = "created"
    CWE = "cwe"
    DATE = "date"
    DUPLICATE = "duplicate"
    DYNAMIC_FINDING = "dynamic_finding"
    FALSE_P = "false_p"
    FOUND_BY = "found_by"
    ID = "id"
    IS_MITIGATED = "is_mitigated"
    LAST_REVIEWED = "last_reviewed"
    LAST_STATUS_UPDATE = "last_status_update"
    NUMERICAL_SEVERITY = "numerical_severity"
    OUT_OF_SCOPE = "out_of_scope"
    REVIEWERS = "reviewers"
    SEVERITY = "severity"
    STATIC_FINDING = "static_finding"
    TEST_ENGAGEMENT_PRODUCT_NAME = "test__engagement__product__name"
    TITLE = "title"
    UNDER_DEFECT_REVIEW = "under_defect_review"
    UNDER_REVIEW = "under_review"
    VALUE_0 = "-active"
    VALUE_1 = "-component_name"
    VALUE_10 = "-id"
    VALUE_11 = "-is_mitigated"
    VALUE_12 = "-last_reviewed"
    VALUE_13 = "-last_status_update"
    VALUE_14 = "-numerical_severity"
    VALUE_15 = "-out_of_scope"
    VALUE_16 = "-reviewers"
    VALUE_17 = "-severity"
    VALUE_18 = "-static_finding"
    VALUE_19 = "-test__engagement__product__name"
    VALUE_2 = "-component_version"
    VALUE_20 = "-title"
    VALUE_21 = "-under_defect_review"
    VALUE_22 = "-under_review"
    VALUE_23 = "-verified"
    VALUE_3 = "-created"
    VALUE_4 = "-cwe"
    VALUE_5 = "-date"
    VALUE_6 = "-duplicate"
    VALUE_7 = "-dynamic_finding"
    VALUE_8 = "-false_p"
    VALUE_9 = "-found_by"
    VERIFIED = "verified"

    def __str__(self) -> str:
        return str(self.value)
