from enum import Enum


class ProductsListOItem(str, Enum):
    BUSINESS_CRITICALITY = "business_criticality"
    CREATED = "created"
    EXTERNAL_AUDIENCE = "external_audience"
    ID = "id"
    INTERNET_ACCESSIBLE = "internet_accessible"
    LIFECYCLE = "lifecycle"
    NAME = "name"
    ORIGIN = "origin"
    PLATFORM = "platform"
    PRODUCT_MANAGER = "product_manager"
    PRODUCT_MANAGER_FIRST_NAME = "product_manager__first_name"
    PRODUCT_MANAGER_LAST_NAME = "product_manager__last_name"
    PROD_NUMERIC_GRADE = "prod_numeric_grade"
    PROD_TYPE = "prod_type"
    PROD_TYPE_NAME = "prod_type__name"
    REVENUE = "revenue"
    TEAM_MANAGER = "team_manager"
    TEAM_MANAGER_FIRST_NAME = "team_manager__first_name"
    TEAM_MANAGER_LAST_NAME = "team_manager__last_name"
    TECHNICAL_CONTACT = "technical_contact"
    TECHNICAL_CONTACT_FIRST_NAME = "technical_contact__first_name"
    TECHNICAL_CONTACT_LAST_NAME = "technical_contact__last_name"
    TID = "tid"
    UPDATED = "updated"
    USER_RECORDS = "user_records"
    VALUE_0 = "-business_criticality"
    VALUE_1 = "-created"
    VALUE_10 = "-prod_type"
    VALUE_11 = "-prod_type__name"
    VALUE_12 = "-product_manager"
    VALUE_13 = "-product_manager__first_name"
    VALUE_14 = "-product_manager__last_name"
    VALUE_15 = "-revenue"
    VALUE_16 = "-team_manager"
    VALUE_17 = "-team_manager__first_name"
    VALUE_18 = "-team_manager__last_name"
    VALUE_19 = "-technical_contact"
    VALUE_2 = "-external_audience"
    VALUE_20 = "-technical_contact__first_name"
    VALUE_21 = "-technical_contact__last_name"
    VALUE_22 = "-tid"
    VALUE_23 = "-updated"
    VALUE_24 = "-user_records"
    VALUE_3 = "-id"
    VALUE_4 = "-internet_accessible"
    VALUE_5 = "-lifecycle"
    VALUE_6 = "-name"
    VALUE_7 = "-origin"
    VALUE_8 = "-platform"
    VALUE_9 = "-prod_numeric_grade"

    def __str__(self) -> str:
        return str(self.value)
